<%@ Page Language="C#" AutoEventWireup="true" CodeFile="dateofbirth.aspx.cs" Inherits="dateofbirth" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table>
            <tr>
                <td>
                    DateOfBirth
                </td>
                <td>
                    <asp:DropDownList ID="ddl_day" runat="server">
                        <asp:ListItem>Day</asp:ListItem>
                        <asp:ListItem>01</asp:ListItem>
                        <asp:ListItem>02</asp:ListItem>
                        <asp:ListItem>03</asp:ListItem>
                        <asp:ListItem>04</asp:ListItem>
                        <asp:ListItem>05</asp:ListItem>
                        <asp:ListItem>06</asp:ListItem>
                        <asp:ListItem>07</asp:ListItem>
                        <asp:ListItem>08</asp:ListItem>
                        <asp:ListItem>09</asp:ListItem>
                        <asp:ListItem>10</asp:ListItem>
                        <asp:ListItem>11</asp:ListItem>
                        <asp:ListItem>12</asp:ListItem>
                        <asp:ListItem>13</asp:ListItem>
                        <asp:ListItem>14</asp:ListItem>
                        <asp:ListItem>15</asp:ListItem>
                        <asp:ListItem>16</asp:ListItem>
                        <asp:ListItem>17</asp:ListItem>
                        <asp:ListItem>18</asp:ListItem>
                        <asp:ListItem>19</asp:ListItem>
                        <asp:ListItem>20</asp:ListItem>
                        <asp:ListItem>21</asp:ListItem>
                        <asp:ListItem>22</asp:ListItem>
                        <asp:ListItem>23</asp:ListItem>
                        <asp:ListItem>24</asp:ListItem>
                        <asp:ListItem>25</asp:ListItem>
                        <asp:ListItem>26</asp:ListItem>
                        <asp:ListItem>27</asp:ListItem>
                        <asp:ListItem>28</asp:ListItem>
                        <asp:ListItem>29</asp:ListItem>
                        <asp:ListItem>30</asp:ListItem>
                        <asp:ListItem>31</asp:ListItem>
                    </asp:DropDownList>
                    <asp:DropDownList ID="ddl_month" runat="server">
                        <asp:ListItem>Month</asp:ListItem>
                        <asp:ListItem>Jan</asp:ListItem>
                        <asp:ListItem>Feb</asp:ListItem>
                        <asp:ListItem>Mar</asp:ListItem>
                        <asp:ListItem>Apr</asp:ListItem>
                        <asp:ListItem>May</asp:ListItem>
                        <asp:ListItem>Jun</asp:ListItem>
                        <asp:ListItem>Jul</asp:ListItem>
                        <asp:ListItem>Aug</asp:ListItem>
                        <asp:ListItem>Sep</asp:ListItem>
                        <asp:ListItem>Oct</asp:ListItem>
                        <asp:ListItem>Nav</asp:ListItem>
                        <asp:ListItem>Dec</asp:ListItem>
                    </asp:DropDownList>
                    <asp:DropDownList ID="ddl_year" runat="server">
                        <asp:ListItem>Year</asp:ListItem>
                        <asp:ListItem>1930</asp:ListItem>
                        <asp:ListItem>1931</asp:ListItem>
                        <asp:ListItem>1932</asp:ListItem>
                        <asp:ListItem>1933</asp:ListItem>
                        <asp:ListItem>1934</asp:ListItem>
                        <asp:ListItem>1935</asp:ListItem>
                        <asp:ListItem>1936</asp:ListItem>
                        <asp:ListItem>1937</asp:ListItem>
                        <asp:ListItem>1938</asp:ListItem>
                        <asp:ListItem>1939</asp:ListItem>
                        <asp:ListItem>1940</asp:ListItem>
                        <asp:ListItem>1941</asp:ListItem>
                        <asp:ListItem>1942</asp:ListItem>
                        <asp:ListItem>1943</asp:ListItem>
                        <asp:ListItem>1944</asp:ListItem>
                        <asp:ListItem>1945</asp:ListItem>
                        <asp:ListItem>1946</asp:ListItem>
                        <asp:ListItem>1947</asp:ListItem>
                        <asp:ListItem>1948</asp:ListItem>
                        <asp:ListItem>1949</asp:ListItem>
                        <asp:ListItem>1950</asp:ListItem>
                        <asp:ListItem>1951</asp:ListItem>
                        <asp:ListItem>1952</asp:ListItem>
                        <asp:ListItem>1953</asp:ListItem>
                        <asp:ListItem>1954</asp:ListItem>
                        <asp:ListItem>1955</asp:ListItem>
                        <asp:ListItem>1956</asp:ListItem>
                        <asp:ListItem>1957</asp:ListItem>
                        <asp:ListItem>1958</asp:ListItem>
                        <asp:ListItem>1959</asp:ListItem>
                        <asp:ListItem>1960</asp:ListItem>
                        <asp:ListItem>1961</asp:ListItem>
                        <asp:ListItem>1962</asp:ListItem>
                        <asp:ListItem>1963</asp:ListItem>
                        <asp:ListItem>1964</asp:ListItem>
                        <asp:ListItem>1965</asp:ListItem>
                        <asp:ListItem>1966</asp:ListItem>
                        <asp:ListItem>1967</asp:ListItem>
                        <asp:ListItem>1968</asp:ListItem>
                        <asp:ListItem>1969</asp:ListItem>
                        <asp:ListItem>1970</asp:ListItem>
                        <asp:ListItem>1971</asp:ListItem>
                        <asp:ListItem>1972</asp:ListItem>
                        <asp:ListItem>1973</asp:ListItem>
                        <asp:ListItem>1974</asp:ListItem>
                        <asp:ListItem>1975</asp:ListItem>
                        <asp:ListItem>1976</asp:ListItem>
                        <asp:ListItem>1977</asp:ListItem>
                        <asp:ListItem>1978</asp:ListItem>
                        <asp:ListItem>1979</asp:ListItem>
                        <asp:ListItem>1980</asp:ListItem>
                        <asp:ListItem>1981</asp:ListItem>
                        <asp:ListItem>1982</asp:ListItem>
                        <asp:ListItem>1983</asp:ListItem>
                        <asp:ListItem>1984</asp:ListItem>
                        <asp:ListItem>1985</asp:ListItem>
                        <asp:ListItem>1986</asp:ListItem>
                        <asp:ListItem>1987</asp:ListItem>
                        <asp:ListItem>1988</asp:ListItem>
                        <asp:ListItem>1989</asp:ListItem>
                        <asp:ListItem>1990</asp:ListItem>
                        <asp:ListItem>1991</asp:ListItem>
                        <asp:ListItem>1992</asp:ListItem>
                        <asp:ListItem>1993</asp:ListItem>
                        <asp:ListItem>1994</asp:ListItem>
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td>
                    Total Work Expirince
                </td>
                <td>
                    <asp:DropDownList ID="ddl_work_year" runat="server">
                        <asp:ListItem>Select Year</asp:ListItem>
                        <asp:ListItem>Fresher</asp:ListItem>
                        <asp:ListItem>0Years</asp:ListItem>
                        <asp:ListItem>1Years</asp:ListItem>
                        <asp:ListItem>2Years</asp:ListItem>
                        <asp:ListItem>3Years</asp:ListItem>
                        <asp:ListItem>4Years</asp:ListItem>
                        <asp:ListItem>5Years</asp:ListItem>
                        <asp:ListItem>6Years</asp:ListItem>
                        <asp:ListItem>7Years</asp:ListItem>
                        <asp:ListItem>8Years</asp:ListItem>
                        <asp:ListItem>9Years</asp:ListItem>
                        <asp:ListItem>10Years</asp:ListItem>
                        <asp:ListItem>11Years</asp:ListItem>
                        <asp:ListItem>12Years</asp:ListItem>
                        <asp:ListItem>13Years</asp:ListItem>
                        <asp:ListItem>14Years</asp:ListItem>
                        <asp:ListItem>15Years</asp:ListItem>
                        <asp:ListItem>16Years</asp:ListItem>
                        <asp:ListItem>17Years</asp:ListItem>
                        <asp:ListItem>18Years</asp:ListItem>
                        <asp:ListItem>19Years</asp:ListItem>
                        <asp:ListItem>20Years</asp:ListItem>
                        <asp:ListItem>21Years</asp:ListItem>
                        <asp:ListItem>22Years</asp:ListItem>
                        <asp:ListItem>23Years</asp:ListItem>
                        <asp:ListItem>24Years</asp:ListItem>
                        <asp:ListItem>25Years</asp:ListItem>
                        <asp:ListItem>26Years</asp:ListItem>
                        <asp:ListItem>27Years</asp:ListItem>
                        <asp:ListItem>28Years</asp:ListItem>
                        <asp:ListItem>29Years</asp:ListItem>
                        <asp:ListItem>30Years</asp:ListItem>
                    </asp:DropDownList>
                    <asp:DropDownList ID="ddl_work_month" runat="server">
                        <asp:ListItem>SelectMonth</asp:ListItem>
                        <asp:ListItem>1Months</asp:ListItem>
                        <asp:ListItem>2Months</asp:ListItem>
                        <asp:ListItem>3Months</asp:ListItem>
                        <asp:ListItem>4Months</asp:ListItem>
                        <asp:ListItem>5Months</asp:ListItem>
                        <asp:ListItem>6Months</asp:ListItem>
                        <asp:ListItem>7Months</asp:ListItem>
                        <asp:ListItem>8Months</asp:ListItem>
                        <asp:ListItem>9Months</asp:ListItem>
                        <asp:ListItem>10Months</asp:ListItem>
                        <asp:ListItem>11Months</asp:ListItem>
                        <asp:ListItem>12Months</asp:ListItem>
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td>
                    Current Annual Salary
                </td>
                <td>
                    <asp:DropDownList ID="ddl_lakh" runat="server">
                        <asp:ListItem>Lakhs</asp:ListItem>
                        <asp:ListItem>1Lakhs</asp:ListItem>
                        <asp:ListItem>2Lakhs</asp:ListItem>
                        <asp:ListItem>3Lakhs</asp:ListItem>
                        <asp:ListItem>4Lakhs</asp:ListItem>
                        <asp:ListItem>5Lakhs</asp:ListItem>
                        <asp:ListItem>6Lakhs</asp:ListItem>
                        <asp:ListItem>7Lakhs</asp:ListItem>
                        <asp:ListItem>8Lakhs</asp:ListItem>
                        <asp:ListItem>9Lakhs</asp:ListItem>
                        <asp:ListItem>10Lakhs</asp:ListItem>
                        <asp:ListItem>11Lakhs</asp:ListItem>
                        <asp:ListItem>12Lakhs</asp:ListItem>
                        <asp:ListItem>13Lakhs</asp:ListItem>
                        <asp:ListItem>14Lakhs</asp:ListItem>
                        <asp:ListItem>15Lakhs</asp:ListItem>
                        <asp:ListItem>16Lakhs</asp:ListItem>
                        <asp:ListItem>17Lakhs</asp:ListItem>
                        <asp:ListItem>18Lakhs</asp:ListItem>
                        <asp:ListItem>19Lakhs</asp:ListItem>
                        <asp:ListItem>20Lakhs</asp:ListItem>
                        <asp:ListItem>21Lakhs</asp:ListItem>
                        <asp:ListItem>22Lakhs</asp:ListItem>
                        <asp:ListItem>23Lakhs</asp:ListItem>
                        <asp:ListItem>24Lakhs</asp:ListItem>
                        <asp:ListItem>25Lakhs</asp:ListItem>
                        <asp:ListItem>26Lakhs</asp:ListItem>
                        <asp:ListItem>27Lakhs</asp:ListItem>
                        <asp:ListItem>28Lakhs</asp:ListItem>
                        <asp:ListItem>29Lakhs</asp:ListItem>
                        <asp:ListItem>30Lakhs</asp:ListItem>
                        <asp:ListItem>31Lakhs</asp:ListItem>
                        <asp:ListItem>32Lakhs</asp:ListItem>
                        <asp:ListItem>33Lakhs</asp:ListItem>
                        <asp:ListItem>34Lakhs</asp:ListItem>
                        <asp:ListItem>35Lakhs</asp:ListItem>
                        <asp:ListItem>36Lakhs</asp:ListItem>
                        <asp:ListItem>37Lakhs</asp:ListItem>
                        <asp:ListItem>38Lakhs</asp:ListItem>
                        <asp:ListItem>39Lakhs</asp:ListItem>
                        <asp:ListItem>40Lakhs</asp:ListItem>
                        <asp:ListItem>41Lakhs</asp:ListItem>
                        <asp:ListItem>42Lakhs</asp:ListItem>
                        <asp:ListItem>43Lakhs</asp:ListItem>
                        <asp:ListItem>44Lakhs</asp:ListItem>
                        <asp:ListItem>45Lakhs</asp:ListItem>
                        <asp:ListItem>46Lakhs</asp:ListItem>
                        <asp:ListItem>47Lakhs</asp:ListItem>
                        <asp:ListItem>48Lakhs</asp:ListItem>
                        <asp:ListItem>49Lakhs</asp:ListItem>
                        <asp:ListItem>50Lakhs</asp:ListItem>
                    </asp:DropDownList>
                    <asp:DropDownList ID="ddl_thousand" runat="server">
                        <asp:ListItem>Thousands</asp:ListItem>
                        <asp:ListItem>0Thousands</asp:ListItem>
                        <asp:ListItem>5Thousands</asp:ListItem>
                        <asp:ListItem>10Thousands</asp:ListItem>
                        <asp:ListItem>15Thousands</asp:ListItem>
                        <asp:ListItem>20Thousands</asp:ListItem>
                        <asp:ListItem>25Thousands</asp:ListItem>
                        <asp:ListItem>30Thousands</asp:ListItem>
                        <asp:ListItem>35Thousands</asp:ListItem>
                        <asp:ListItem>40Thousands</asp:ListItem>
                        <asp:ListItem>45Thousands</asp:ListItem>
                        <asp:ListItem>50Thousands</asp:ListItem>
                        <asp:ListItem>55Thousands</asp:ListItem>
                        <asp:ListItem>60Thousands</asp:ListItem>
                        <asp:ListItem>65Thousands</asp:ListItem>
                        <asp:ListItem>70Thousands</asp:ListItem>
                        <asp:ListItem>75Thousands</asp:ListItem>
                        <asp:ListItem>80Thousands</asp:ListItem>
                        <asp:ListItem>85Thousands</asp:ListItem>
                        <asp:ListItem>90Thousands</asp:ListItem>
                        <asp:ListItem>95Thousands</asp:ListItem>
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Button ID="btn_submit" runat="server" Text="Submit" nClick="btn_submit_Click" />
                    <asp:Button ID="btn_update" runat="server" Text="Update" OnClick="btn_update_Click" />
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AllowPaging="true"
                        PageSize="5" DataKeyNames="code" OnRowEditing="GridView1_RowEditing" OnRowDeleting="GridView1_RowDeleting"
                        OnPageIndexChanging="GridView1_PageIndexChanging">
                        <Columns>
                            <asp:CommandField HeaderText="Delete" ShowDeleteButton="true" ButtonType="Link" />
                            <asp:CommandField HeaderText="Edit" ShowEditButton="true" ButtonType="Link" />
                            <asp:BoundField HeaderText="DateOFBirth" DataField="dateofbirth" />
                            <asp:BoundField HeaderText="TotalWork" DataField="totalwork" />
                            <asp:BoundField HeaderText="Salary" DataField="salary" />
                        </Columns>
                    </asp:GridView>
                </td>"
            </tr>
        </table>
    </div>
    </form>
</body>
</html>
